### ISSUE TITLE
Better support for extras in the upgrade portion

### ISSUE THREAD

**Issue by fdosani** [capitalone/edgetest#14]
Right now if you want to upgrade a package which has `mypackage[extras]` you need to update it as `mypackage`. I think we can provide better support for the `extras` to align better as there could be cases where the items in `extras` are not being bumped properly.

@ak-gupta thoughts?

**Comment by fdosani** [comment]
@ak-gupta So I'm thinking we can add something like the following here: https://github.com/capitalone/edgetest/blob/dev/edgetest/core.py#L152

```python
pattern = "\[.+\]"
upgrade_wo_extras = [re.sub(pattern, "", pkg) for pkg in self.upgrade]
return [pkg for pkg in outjson if pkg.get("name", "") in upgrade_wo_extras]
```

In the current code something like `dask[dataframe]` does not pass the conditional in the list comprehension. 

```python
return [pkg for pkg in outjson if pkg.get("name", "") in self.upgrade]
```
It works out to something like this:

```python
In [1]: upgrade = ['dask[dataframe]']

In [2]: pkg_from_pip = {'name': 'dask', 'version': '2022.3.0'}

In [3]: pkg_from_pip.get("name", "") in upgrade
Out[3]: False
```

**Comment by ak-gupta** [comment]
Yeah that should work. My first thought it `pkg.split("[")[0]` could be simpler but either should fix the problem

**Comment by ak-gupta** [comment]
We should also validate that the upgrading doesn't nuke the extra from the requirements. From looking at the `pkg_resources.parse_requirements` function it _shouldn't_, but maybe we add an extra to one of the upgrade packages in the integration testing to make sure

**Comment by fdosani** [comment]
I'm all for simpler code and one less import. :)
