### ISSUE TITLE
edgetest force pushes overwrite user commits

### ISSUE THREAD

**Issue by ryanSoley** [capitalone/edgetest#22]
edgetest opened this PR to update the `dask[dataframe]` version yesterday
> https://github.com/capitalone/rubicon-ml/pull/221

I had to manually apply those version updates to the environment files in my repo, which caused the whitesource scan to fail. so, I left the PR open overnight to come back to it today and finish. overnight, edgetest again noticed that `dask[dataframe]` needed to be updated so it created a branch with the same name as the one I had committed my manual changes to yesterday and forced pushed, overwriting the branch

edgetest should be able to recognize that it already opened the PR to update `dask[dataframe]` and not force push the same update

I also imagine that if a second library needed to be updated while the PR for a previous one is still open we'd see the same behavior since the branch always seems to be named `edgetest-patch`

**Comment by fdosani** [comment]
This is more of the functionality of the action https://github.com/fdosani/run-edgetest-action. I'll close this one and open an issue there
