### ISSUE TITLE
pip packages should be case insensitive and `_` vs `-` are the same

### ISSUE THREAD

**Issue by fdosani** [capitalone/edgetest#63]
There is a minor bug/corner case where the package name's case setting affects if it gets picked up.

From https://peps.python.org/pep-0426/#name

> All comparisons of distribution names MUST be case insensitive, and MUST consider hyphens and underscores to be equivalent.

Example:
- `Numpy` == `numpy` == `NuMPy`
- `My-package` == `my_package`

@ak-gupta or @NikhilJArora would you have time/interest to work on a fix for this?

**Comment by NikhilJArora** [comment]
I'd be interested in taking a look at this!

**Comment by fdosani** [comment]
> I'd be interested in taking a look at this!

Thanks @NikhilJArora that would be fantastic
